export const RELIGIONS = [
  "Hindu",
  "Muslim",
  "Sikh",
  "Christian",
  "Jain",
  "Buddhist",
  "Parsi",
  "Jewish",
  "Other",
];

export const CASTES = {
  Hindu: [
    "Brahmin",
    "Kshatriya",
    "Vaishya",
    "Shudra",
    "Kayastha",
    "Rajput",
    "Maratha",
    "Jat",
    "Yadav",
    "Kurmi",
    "Patel",
    "Reddy",
    "Nair",
    "Iyer",
    "Iyengar",
    "Lingayat",
    "Gowda",
    "Mudaliar",
    "Nadar",
    "Other",
  ],
  Muslim: ["Sunni", "Shia", "Ismaili", "Ahmadiyya", "Sufi", "Other"],
  Sikh: [
    "Jat Sikh",
    "Khatri Sikh",
    "Arora Sikh",
    "Ramgarhia",
    "Ramdasia",
    "Other",
  ],
  Christian: ["Catholic", "Protestant", "Orthodox", "Evangelical", "Other"],
  Jain: ["Digambara", "Shwetambara", "Other"],
  Buddhist: ["Theravada", "Mahayana", "Vajrayana", "Other"],
  default: ["Not Specified", "Other"],
};

export const RASHIS = [
  "Mesh (Aries)",
  "Vrishabh (Taurus)",
  "Mithun (Gemini)",
  "Kark (Cancer)",
  "Simha (Leo)",
  "Kanya (Virgo)",
  "Tula (Libra)",
  "Vrischik (Scorpio)",
  "Dhanu (Sagittarius)",
  "Makar (Capricorn)",
  "Kumbha (Aquarius)",
  "Meen (Pisces)",
];

export const NAKSHATRAS = [
  "Ashwini",
  "Bharani",
  "Krittika",
  "Rohini",
  "Mrigashira",
  "Ardra",
  "Punarvasu",
  "Pushya",
  "Ashlesha",
  "Magha",
  "Purva Phalguni",
  "Uttara Phalguni",
  "Hasta",
  "Chitra",
  "Swati",
  "Vishakha",
  "Anuradha",
  "Jyeshtha",
  "Mula",
  "Purva Ashadha",
  "Uttara Ashadha",
  "Shravana",
  "Dhanishtha",
  "Shatabhisha",
  "Purva Bhadrapada",
  "Uttara Bhadrapada",
  "Revati",
];

export const BLOOD_GROUPS = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];

export const HEIGHTS = [
  "4'6\"",
  "4'7\"",
  "4'8\"",
  "4'9\"",
  "4'10\"",
  "4'11\"",
  "5'0\"",
  "5'1\"",
  "5'2\"",
  "5'3\"",
  "5'4\"",
  "5'5\"",
  "5'6\"",
  "5'7\"",
  "5'8\"",
  "5'9\"",
  "5'10\"",
  "5'11\"",
  "6'0\"",
  "6'1\"",
  "6'2\"",
  "6'3\"",
  "6'4\"",
  "6'5\"",
];

export const COMPLEXIONS = [
  "Very Fair",
  "Fair",
  "Wheatish",
  "Wheatish Brown",
  "Brown",
  "Dark",
];

export const MARITAL_STATUS = [
  "Never Married",
  "Divorced",
  "Widowed",
  "Separated",
];

export const FAMILY_TYPES = ["Nuclear", "Joint", "Extended"];

export const FAMILY_STATUS = [
  "Middle Class",
  "Upper Middle Class",
  "Rich",
  "Affluent",
];

export const MANGLIK = ["No", "Yes", "Partial (Anshik)", "Not Known"];

export const GENDERS = ["Male", "Female"];

export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Delhi",
  "Jammu & Kashmir",
  "Ladakh",
  "Puducherry",
  "Chandigarh",
  "Other",
];

export const INCOME_RANGES = [
  "Below ₹2 LPA",
  "₹2-5 LPA",
  "₹5-10 LPA",
  "₹10-15 LPA",
  "₹15-25 LPA",
  "₹25-50 LPA",
  "Above ₹50 LPA",
  "Prefer not to say",
];

export const EDUCATION_LEVELS = [
  "Below 10th",
  "10th Pass",
  "12th Pass",
  "Diploma",
  "ITI",
  "Bachelor's Degree",
  "Master's Degree",
  "MBA",
  "M.Tech/ME",
  "PhD",
  "MBBS/MD",
  "LLB/LLM",
  "CA/CPA",
  "Other",
];

export const MOTHER_TONGUES = [
  "Hindi",
  "Bengali",
  "Marathi",
  "Telugu",
  "Tamil",
  "Gujarati",
  "Urdu",
  "Kannada",
  "Odia",
  "Malayalam",
  "Punjabi",
  "Assamese",
  "Maithili",
  "Sanskrit",
  "Other",
];

export const BLANK_FORM = {
  // Personal
  name: "",
  gender: "",
  dob: "",
  age: "",
  height: "",
  complexion: "",
  bloodGroup: "",
  religion: "",
  caste: "",
  motherTongue: "",
  maritalStatus: "",
  nationality: "Indian",
  about: "",
  // Education
  education: "",
  college: "",
  profession: "",
  company: "",
  income: "",
  hideIncome: false,
  // Family
  fatherName: "",
  fatherOccupation: "",
  motherName: "",
  motherOccupation: "",
  siblings: "",
  familyType: "",
  familyStatus: "",
  nativePlace: "",
  // Horoscope
  rashi: "",
  nakshatra: "",
  gothra: "",
  manglik: "",
  birthTime: "",
  birthPlace: "",
  // Contact
  contactEmail: "",
  phone: "",
  address: "",
  city: "",
  state: "",
  hideContact: false,
  // Template
  template: 1,
  // Photo
  photo: "",
};
